name: Test

on:
  push:
    branches:
      - 'feature/*'
      - 'fix/*'
      - 'hotfix/*'
      - 'release/*'

jobs:
  test:
    strategy:
      matrix:
        version: ['8.1', '8.2', '8.3']
    environment:
      name: Test
    runs-on: ubuntu-latest
    if: ${{ github.ref != 'refs/heads/trunk' }}
    steps:
      - name: Check credentials
        id: docker-credentials
        run: |
          echo ::set-output name=defined::$(test -n "${{ secrets.DOCKERHUB_USERNAME }}" && echo true || echo false)

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        if: steps.docker-credentials.outputs.defined == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        if: steps.docker-credentials.outputs.defined == 'true'
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=raw,pattern={{version}},value=test-${{ github.sha }}
          images: |
            ${{ secrets.IMAGE_NAME }}

      - name: Build and push Docker images
        if: steps.docker-credentials.outputs.defined == 'true'
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
